# Generated by Django 2.1.4 on 2018-12-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_convert_author_string_to_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_string',
        ),
    ]
